using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler.Problems
{
    internal class Problem2
    {
        public int Solve()
        {
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            //Answer: 4613732

            int fibonacciFirst = 1;
            int fibonacciSecond = 1;
            int fibonacciThird = 2;
            var fibonacciList = new List<int>();

            while (true)
            {
                fibonacciThird = fibonacciFirst + fibonacciSecond;
                if (fibonacciThird > 4000000)
                    break;
                fibonacciFirst = fibonacciSecond;
                fibonacciSecond = fibonacciThird;

                if (fibonacciThird % 2 == 0)
                {
                    fibonacciList.Add(fibonacciThird);
                }
            }

            return fibonacciList.Sum();
        }
    }
}